[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.portray]
extra_dirs = ["examples"]
modules = ["dicebear"]
output_dir = "docs"

[tool.portray.mkdocs.theme]
favicon = "images/favicon.svg"
logo = "images/favicon.svg"
name = "material"